### ISSUE TITLE
Release data inquiry

### ISSUE THREAD

**Issue by gyupro** [xuebinqin/DIS#1]
Hi, xuebinqin.

I have been following your great work since U-2-Net, I really appreciate it and learn a lot from it

I just found out you are about to release your DIS repo. 

I was wondering when you plan to release it and how you got your segmentation data using GIMP.

Can you let me know what was the procedure to get the segmentation data?? did you use specific GIMP-plugin (U-2-NET) or guided-segmentation?

I am actually planning to get high-quality segmentation data and wondering how you figured out.

Thanks in advance.

**Comment by Abbsalehi** [comment]
@gyupro @xuebinqin could you please share a link to the tutorial on how to make the training masks?
