### ISSUE TITLE
Dataset image format issues

### ISSUE THREAD

**Issue by babyta** [xuebinqin/DIS#102]
'''
if datasets[i]["im_ext"]!=".png" or datasets[i]["gt_ext"]!=".png":
                    print("Error: Please make sure all you images and ground truth masks are in jpg and png format respectively !!!")
                    exit()
'''
I want to ensure the quality of the image, so my original image is in png format. Is it necessary to ensure the jpg format here? Currently I changed the code 'jpg' to 'png'

**Comment by Sencc** [comment]
I think the image format is not important, you can modify it to what you need.

**Comment by babyta** [comment]
yeah,I commented him out
