### ISSUE TITLE
Need Suggestion for Result on High Resolution Images

### ISSUE THREAD

**Issue by Kaustubh-cpu** [xuebinqin/DIS#127]
@xuebinqin @DengPingFan @PINTO0309 @16673161214 @HUuxiaobin 

Hello Auther's,

I am trying to get the result on the high resolution images but with this configuration i am not at all getting the good result . Getting some zigzag pattern in the selection where as line should be straight 
![Screenshot 2024-05-22 113805](https://github.com/xuebinqin/DIS/assets/139736091/c8c8ddb3-e7f5-4820-8d29-e40ec68381ea)

please if you have any idea suggest me how i can result on the high resolution images also as this model is only capable of giving the result till 2048 if i have trained the model on 1024 ....... if i am trying to do the inference on the more than 3000 resolution images then there is ZIGZAG staircase which making the model very less accurate 

kindly reply for this if you have any suggestion for me

**Comment by muhammadhassan999** [comment]
thank you for creating an issue in my usecase i've both high level img and low resolution imgs.

**Comment by Kaustubh-cpu** [comment]
@muhammadhassan999 

Do you have any idea how to deal with this problem

**Comment by muhammadhassan999** [comment]
what i think, given image need to more preprocssing step to feed the pretrained model to get an optmized removal of background.

**Comment by Kaustubh-cpu** [comment]
@xuebinqin @DengPingFan @HUuxiaobin @

Is there any one who can reply for this issue from the team 
As this is the very series issue if this model is not giving the result on the 2048 also if i train it on 1024 then there is no point to use this model .................. @xuebinqin @DengPingFan @HUuxiaobin At least reply on the issue

**Comment by Kaustubh-cpu** [comment]
@xuebinqin @DengPingFan @HUuxiaobin @

Is there any one who can reply for this issue from the team 
As this is the very series issue if this model is not giving the result on the 2048 also if i train it on 1024 then there is no point to use this model .................. @xuebinqin @DengPingFan @HUuxiaobin At least reply on the issue
