### ISSUE TITLE
Weird result after 30 epochs

### ISSUE THREAD

**Issue by ogladkov** [xuebinqin/DIS#57]
Hi guys! Please advice if you know what happens and did trained the network. 
The problem is that: I train DIS with ade20k dataset with only floor category (0 value or 255 for the floor) and after more than 30 epochs (there are some  25000 imgs for an epopch) i got that result (please see screenshots).
I got my loss decreasing but it couldn't go below 3.0.
Who knows what's wrong? Thank you!

![11](https://user-images.githubusercontent.com/39189447/200235858-771ff6f0-779b-40a3-928d-0aaed93cb3c2.png)

![12](https://user-images.githubusercontent.com/39189447/200235897-13f1ed7d-8173-4518-8905-27f560eb9d60.png)

![13](https://user-images.githubusercontent.com/39189447/200235916-cf37215c-4d78-4b6d-b432-4bfea5203413.png)

**Comment by ChristianGerdes** [comment]
Can you share your code so other people can contribute in solving the issue?

**Comment by ogladkov** [comment]
The problem was solved. There was low F1 due to '*255' problem that was eliminated in this repo by author of the net.
