### ISSUE TITLE
windows is not supported?

### ISSUE THREAD

**Issue by Ratinod** [xuebinqin/DIS#70]
When i use command:
`conda env create -f pytorch18.yml`
i get this:
```
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - ca-certificates==2022.2.1=h06a4308_0
  - brotli==1.0.9=he6710b0_2
  - ...
```
I went to the conda site and looked for the first package "_openmp_mutex"  https://anaconda.org/search?q=_openmp_mutex
and... this package does not exist for win64.
I understand correctly that at the moment installing and running DIS on windows is not possible?
Maybe somehow you can manually make it work without conda, but using venv?
How critical is "_openmp_mutex" for DIS to work?

**Comment by swframe** [comment]
Correct. It runs only on wsl because of some linux only dependencies. As you probably know wsl2.0 has a gpu passthrough.

**Comment by Boxser567** [comment]
> When i use command: `conda env create -f pytorch18.yml` i get this:
> 
> ```
> Collecting package metadata (repodata.json): done
> Solving environment: failed
> 
> ResolvePackageNotFound:
>   - ca-certificates==2022.2.1=h06a4308_0
>   - brotli==1.0.9=he6710b0_2
>   - ...
> ```
> 
> I went to the conda site and looked for the first package "_openmp_mutex" https://anaconda.org/search?q=_openmp_mutex and... this package does not exist for win64. I understand correctly that at the moment installing and running DIS on windows is not possible? Maybe somehow you can manually make it work without conda, but using venv? How critical is "_openmp_mutex" for DIS to work?


@swframe 
Yes, I had the same problem with my macbook pro 2018.
Intel Core i7, Radeon Pro 560X 4 GB, Intel UHD Graphics 630 1536 MB

**Comment by hjj-lmx** [comment]
> 我在 Windows 11 上运行 DIS 推理和训练，不使用 conda 或 wsl，没有问题

May I ask how to install the Windows environment
